---
- name: add toolchain repository for recent compiler versions
  become: True
  become_user: "{{ root_user }}"
  apt_repository:
    repo: ppa:ubuntu-toolchain-r/test
    state: present

- name: Install libraries
  become: true
  become_user: "{{ root_user }}"
  apt:
      name: "{{ item }}"
      state: latest
      update_cache: True
  with_items:
    # Compilation
    - build-essential
    - python-passlib    
    - gfortran
    - openmpi-common
    - openmpi-bin
    - libopenmpi-dev
    - libfftw3-dev 
    - libfftw3-bin 
    - libfftw3-mpi-dev
    - liblapack-dev
    - libblas-dev
    - m4

- include_role:
    name: release_notes
  vars:
    section: "MPI libraries"
    option: "openmpi"
    value: "Run using 'mpirun <NUMPROCS> <EXECNAME>'"
  when: release_notes is defined and release_notes

