---
- name: "get the machine hostname"
  become: true
  become_user: "{{ root_user }}"
  command: "hostname"
  register: cur_hostname_command
  changed_when: false

# This updates both the current hostname and /etc/hostname
- name: "update machine hostname, if necessary"
  become: true
  become_user: "{{ root_user }}"
  hostname: 
    name: "{{ simulationbase_hostname }}"
  when: cur_hostname_command.stdout != simulationbase_hostname

- name: "remove lines with 127.0.1.1, except for 127.0.1.1. localhost"
  become: true
  become_user: "{{ root_user }}"
  lineinfile:
    path: "/etc/hosts"
    regexp: '^127\.0\.1\.1 (?!localhost)'
    state: absent

- name: "set 127.0.1.1 to localhost (if it's set to the hostname, pbs server complains)"
  become: true
  become_user: "{{ root_user }}"
  lineinfile:
    path: "/etc/hosts"
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 localhost"

- name: "set hostname for dynamic ip address in /etc/hosts (needed for PBS Torque)"
  become: true
  become_user: "{{ root_user }}"
  lineinfile:
    path: "/etc/hosts"
    # lines ending with hostname
    regexp: "{{ simulationbase_hostname }}$"
    line: "{{ ansible_default_ipv4.address }} {{ simulationbase_hostname }}"
