---
- name: Install plotting tools, etc.
  become: true
  become_user: "{{ root_user }}"
  apt:
    name: 
    # For plotting
    - grace
    - gnuplot
    - python-tk 
    - xcrysden
    # note: jmol+java = 110MB
    - jmol
    - default-jre
    state: present

- include_role: 
    name: release_notes
  vars:
    section: "Plotting Tools"
    option: "available tools"
    value: "xmgrace, gnuplot, xcrysden, jmol"
  when: release_notes is defined and release_notes
