---
- name: Add neurodebian repo
  become: true
  become_user: "{{ root_user }}"
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - deb http://mirror.aarnet.edu.au/pub/neurodebian data main contrib non-free
    # ansible_distribution_release should be either "xenial" or "bionic"
    - deb http://mirror.aarnet.edu.au/pub/neurodebian {{ ansible_distribution_release }} main contrib non-free

- name: Add key for neurodebian repo
  become: true
  become_user: "{{ root_user }}"
  apt_key:
    keyserver: hkp://pool.sks-keyservers.net:80
    id: 0xA5D32F012649A5A9

- name: Update repositories cache & upgrade packages
  become: true
  become_user: "{{ root_user }}"
  apt:
    update_cache: true
    cache_valid_time: 86400  # One day
    name:
      - singularity-container
  notify: apt clean
