---
- name: add packages (pip)
  become: true
  pip:
    name:
      - virtualenv
      - virtualenvwrapper

# This is where `pip install --user` adds executables
- name: Add ~/.local/bin to the PATH
  become: true
  become_user: "{{ simulationbase_vm_user }}"
  lineinfile:
    path: "${HOME}/.bashrc"
    line: "export PATH=$PATH:${HOME}/.local/bin"

- name: "Run virtualenvwrapper once to create folders"
  become: true
  become_user: "{{ simulationbase_vm_user }}"
  command: "bash /usr/local/bin/virtualenvwrapper.sh"
  args:
    creates: "${HOME}/.virtualenvs/initialize"

# This fixes https://github.com/marvel-nccr/marvel-virtualmachine/issues/21
# Note: this is needed for the 'workon' command and thus needs to go in the .bashrc
- name: "Fix virtualenvwrapper python executable"
  become: true
  become_user: "{{ simulationbase_vm_user }}"
  lineinfile:
    path: "${HOME}/.bashrc"
    regexp: "export VIRTUALENVWRAPPER_PYTHON=.*"
    line: "export VIRTUALENVWRAPPER_PYTHON={{ ansible_python_interpreter }}"

# For safety, also put this into .profile (in case this is needed by non-interactive shells)
- name: "Fix virtualenvwrapper python executable"
  become: true
  become_user: "{{ simulationbase_vm_user }}"
  lineinfile:
    path: "${HOME}/.profile"
    regexp: "export VIRTUALENVWRAPPER_PYTHON=.*"
    line: "export VIRTUALENVWRAPPER_PYTHON={{ ansible_python_interpreter }}"

# Note: this provides the 'workon' command and thus needs to go in the .bashrc
- name: "Activate the virtualenvwrapper for the user"
  become: true
  become_user: "{{ simulationbase_vm_user }}"
  lineinfile:
    path: "${HOME}/.bashrc"
    line: "source /usr/local/bin/virtualenvwrapper.sh"
